import { NextPage, GetServerSidePropsContext } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import { requireAuthentication } from '../core/auth/requireAuthentication';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Smart Staking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      </main>

      
    </div>
  )
}

export const getServerSideProps = requireAuthentication((context: GetServerSidePropsContext) => {
  
});

export default Home;